version: "3.3"

volumes:
    sqlite-data:

services:
    web:
        image: "ghcr.io/thomascenni/wordpress-sqlite:latest"
        ports:
            - "8080:80"
        volumes:
            - sqlite-data:/wpsqlitedata
