version: "3.3"

volumes:
    wordpress-data:

services:
    web:
        image: "ghcr.io/thomascenni/wordpress-sqlite:latest"
        environment:
            - SSL_MODE=off
            - WORDPRESS_VERSION=6.7.2
        ports:
            - "8080:80"
        volumes:
            - wordpress-data:/var/www/html/wp-content
