#!/command/with-contenv bash
# https://github.com/just-containers/s6-overlay#container-environment
# Exit on error
set -e

WORDPRESS_ROOT="$WEBUSER_HOME"
WORDPRESS_CHECK="$WORDPRESS_ROOT/wp-admin"

if [ ! -d "$WORDPRESS_CHECK" ]; then
    echo; echo "✨ Installing Wordpress from scratch"
    rm -f $WORDPRESS_ROOT/index.*
    wp core download --allow-root \
        --path=$WORDPRESS_ROOT \
        --locale="${WORDPRESS_LOCALE:-en_US}" \
        --version="${WORDPRESS_VERSION:-6.0.2}" \
        --force
    chown -R $PUID:$PGID $WORDPRESS_ROOT

    echo; echo "✨ Installing wp-sqlite-db from source"
    wget -q -O "$WORDPRESS_ROOT/wp-content/db.php" https://raw.githubusercontent.com/aaemnnosttv/wp-sqlite-db/master/src/db.php

    echo; echo "✨ Creating wp-config.php file"
    wp config create --path=$WORDPRESS_ROOT --allow-root --dbname=wpsqlite --dbuser=wpsqlite --skip-check
else
    echo; echo "✅ Wordpress installation found. Nothing to do."
fi

echo "✅ Done."