name: Build and push Docker image

on:
    push:
        branches: [master]

permissions:
    packages: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              name: Check out code

            - uses: mr-smithers-excellent/docker-build-push@v5
              name: Build & push Docker image
              with:
                  image: ghcr.io/thomascenni/wordpress-sqlite
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GHCR_TOKEN }}
